import { NextResponse } from "next/server";
import { and, eq, isNull } from "drizzle-orm";
import { db } from "@/db";
import { deadlines } from "@/db/schema";
import { notifyDeadline } from "@/lib/notify";

/**
 * Vercel Cron handler — runs daily at 13:00 UTC (configured in vercel.json).
 *
 * For each open deadline:
 *   - if due in 14 days and we haven't sent the 14-day reminder yet, send it
 *   - if due in 7 days and we haven't sent the 7-day reminder yet, send it
 *   - if due in 1 day and we haven't sent the 1-day reminder yet, send it
 *
 * Each reminder is gated by a reminded_<n>_at timestamp on the deadline
 * row, so re-runs (Vercel sometimes retries on transient failures) don't
 * double-send.
 *
 * Auth: Vercel Cron includes `Authorization: Bearer <CRON_SECRET>` on every
 * request. CRON_SECRET is auto-generated by Vercel and exposed as an env
 * var; locally set it to whatever you want for manual testing.
 */
export async function GET(request: Request): Promise<NextResponse> {
  const expected = process.env.CRON_SECRET;
  if (!expected) {
    return NextResponse.json(
      { error: "CRON_SECRET is not configured" },
      { status: 500 },
    );
  }
  if (request.headers.get("authorization") !== `Bearer ${expected}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const targets: Array<{
    days: number;
    column: "reminded14At" | "reminded7At" | "reminded1At";
  }> = [
    { days: 14, column: "reminded14At" },
    { days: 7, column: "reminded7At" },
    { days: 1, column: "reminded1At" },
  ];

  const results: Array<{
    days: number;
    candidates: number;
    sent: number;
    failed: number;
  }> = [];

  for (const { days, column } of targets) {
    const target = formatYMD(addDays(new Date(), days));

    const candidates = await db.query.deadlines.findMany({
      where: and(
        eq(deadlines.dueDate, target),
        isNull(deadlines.completedAt),
        isNull(deadlines[column]),
      ),
    });

    let sent = 0;
    let failed = 0;
    for (const d of candidates) {
      try {
        await notifyDeadline({
          applicationId: d.applicationId,
          deadlineId: d.id,
          deadlineTitle: d.title,
          daysOut: days,
          dueDate: d.dueDate,
          notes: d.notes,
        });
        await db
          .update(deadlines)
          .set({ [column]: new Date() })
          .where(eq(deadlines.id, d.id));
        sent++;
      } catch (err) {
        console.error(
          `[cron/deadline-reminders] failed for ${d.id}:`,
          err,
        );
        failed++;
      }
    }

    results.push({ days, candidates: candidates.length, sent, failed });
  }

  console.log(
    `[cron/deadline-reminders] ${JSON.stringify(results)}`,
  );
  return NextResponse.json({ ok: true, results });
}

function addDays(d: Date, days: number): Date {
  const out = new Date(d);
  out.setDate(out.getDate() + days);
  return out;
}

function formatYMD(d: Date): string {
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}
